import { useTheme } from '@/hooks/useTheme'
import PageHeader from '@/components/layout/PageHeader'
import Card from '@/components/common/Card'
import Button from '@/components/common/Button'
import { useState } from 'react'
import { getDb } from '@/lib/db/indexedDb'

export default function SettingsPage() {
  const { theme, setTheme } = useTheme()
  const [clearing, setClearing] = useState(false)
  const [cleared, setCleared] = useState(false)

  const clearAllData = async () => {
    if (!confirm('This will delete ALL inspections and data stored locally. Are you sure?')) return
    setClearing(true)
    try {
      const db = await getDb()
      const stores = ['inspections', 'assets', 'ocrResults', 'clarityAnnotations', 'symmetryAnalyses', 'certExtractions', 'reports'] as const
      for (const store of stores) {
        await db.clear(store)
      }
      setCleared(true)
      setTimeout(() => setCleared(false), 3000)
    } finally {
      setClearing(false)
    }
  }

  return (
    <div className="max-w-2xl">
      <PageHeader title="Settings" subtitle="Application preferences and data management" />

      <div className="space-y-5">
        <Card header="Appearance">
          <div className="flex items-center justify-between">
            <div>
              <p className="font-medium text-slate-700 dark:text-slate-200">Theme</p>
              <p className="text-sm text-slate-500 dark:text-slate-400">Currently: {theme}</p>
            </div>
            <div className="flex gap-2">
              <Button
                variant={theme === 'light' ? 'primary' : 'secondary'}
                size="sm"
                onClick={() => setTheme('light')}
              >
                Light
              </Button>
              <Button
                variant={theme === 'dark' ? 'primary' : 'secondary'}
                size="sm"
                onClick={() => setTheme('dark')}
              >
                Dark
              </Button>
            </div>
          </div>
        </Card>

        <Card header="About">
          <div className="space-y-2 text-sm text-slate-600 dark:text-slate-400">
            <p><strong className="text-slate-700 dark:text-slate-300">Lab Diamond Checker</strong> v0.1.0</p>
            <p>A client-side diamond quality control application. All data is stored locally in your browser using IndexedDB.</p>
            <p>Built with React, TypeScript, Tailwind CSS, Zustand, react-konva, Tesseract.js, and jsPDF.</p>
          </div>
        </Card>

        <Card header="Data Management">
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="font-medium text-slate-700 dark:text-slate-200">Clear All Data</p>
                <p className="text-sm text-slate-500 dark:text-slate-400">Permanently delete all inspections and stored data.</p>
              </div>
              <Button
                variant="danger"
                size="sm"
                onClick={clearAllData}
                loading={clearing}
              >
                {cleared ? '✓ Cleared' : 'Clear All'}
              </Button>
            </div>
          </div>
        </Card>

        <Card header="Disclaimer">
          <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">
            Lab Diamond Checker is a reference tool for educational and internal QC workflows. Grade estimates, symmetry scores, and clarity assessments generated by this application are not a substitute for certified gemological appraisal by a qualified professional. Always verify results with a certified GIA, IGI, or AGS laboratory report.
          </p>
        </Card>
      </div>
    </div>
  )
}
